version: 2

sources:
    - name: staging
      database: ny-taxi-de-zoomcamp
      schema: trips_data_all
      

      tables:
        - name: green_tripdata_partitoned_clustered
        - name: yellow_tripdata_partitioned_clustered